pipeline{
    agent any
     tools{
        maven 'M2_HOME'
     }
    stages {
        stage("maven"){
            steps{
            sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP5W3QwUNxGwfmEsFDfksXWfvkE -T \
                 target/bio*.jar\
                "http://ec2-100-26-163-246.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
        }
    }
}