pipeline{
    agent any
     tools{
        maven 'M2_HOME'
     }
    stages {
        stage('sonar-scan'){
            steps{
                withSonarQubeEnv('sonarQube'){
                      sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=yatsen24_geo-app'

                }
            }
        }
        stage("maven"){
            steps{
            sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -u<USERNAME>:<PASSWORD> -T \
                 target/bio*.jar "http://ec2-100-24-255-33.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
                
            }
        }
        stage('docker login1'){
            steps{
                sh 'aws ecr get-login-password --region us-east-1 | \
                docker login --username AWS --password-stdin 831354348245.dkr.ecr.us-east-1.amazonaws.com'

            }
        }
    }
}