pipeline{
    agent any
     tools{
        maven 'M2_HOME'
     }
    stages {
        stage('sonar-scan'){
            steps{
                withSonarQubeEnv('sonarQube'){
                      sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=yatsen24_geo-app'

                }
            }
        }
        stage("maven"){
            steps{
            sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP5W3QwUNxGwfmEsFDfksXWfvkE -T \
                target/bio*.jar "http://ec2-100-25-135-11.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio5_${BUILD_ID}.jar"'

            }
        }
        
        stage('docker login'){
            steps{
                sh 'aws ecr get-login-password --region us-east-1 | \
                docker login --username AWS --password-stdin 831354348245.dkr.ecr.us-east-1.amazonaws.com'

            }
        }
        stage('docker build'){
            steps{
                sh 'docker build -t utc-app-dev:v.${BUILD_ID} .'
                sh 'docker build -t utc-app-dev:latest .'
            }
        }
        stage('image tagging'){
            steps{
                sh 'docker tag utc-app-dev:latest 831354348245.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
                sh 'docker tag utc-app-dev:latest \
                831354348245.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
            }
        }
        stage('image push'){
            steps{
                sh 'docker push 831354348245.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
                sh 'docker push 831354348245.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
            }
        }
    }
}